---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cryptone/public_html   # Destination directory
    - export SOURCE_DIR=/home/cryptone/repositories/alphaminers       # Source code directory
    - /bin/rm -rf $DEPLOYPATH/*                  # Remove existing files in the destination
    - /bin/cp -R $SOURCE_DIR/dist/* $DEPLOYPATH  # Copy the Vite React build files to the destination
    - /bin/cp $SOURCE_DIR/dist/index.html $DEPLOYPATH/index.html 